name: Publish to npm

on:
  workflow_call:
    inputs:
      command:
        description: Command to run
        type: string
        required: true
        default: "publish:npm"

jobs:
  publish:
    needs: bump
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          registry-url: https://registry.npmjs.org

      - name: Install dependencies
        run: npm ci

      - name: Publish package
        run: npm run ${{ inputs.command }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
